// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArwfED6RJFnWCi_-Is2U4d4DbNsw3boQs',
    appId: '1:689549972098:web:46be0fe4284842f6389a9b',
    messagingSenderId: '689549972098',
    projectId: 'fooddeliveryapp-1adf4',
    authDomain: 'fooddeliveryapp-1adf4.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-1adf4.appspot.com',
    measurementId: 'G-J1WG9LHYYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB57TXzXB95CyR6GGvMcydbMH6Adc0ZZNk',
    appId: '1:689549972098:android:e1d93ad33fb05cb9389a9b',
    messagingSenderId: '689549972098',
    projectId: 'fooddeliveryapp-1adf4',
    storageBucket: 'fooddeliveryapp-1adf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR44Ehjxtz05NcvOKBFkUeA9fBARJT7h8',
    appId: '1:689549972098:ios:f54e7ccc7bd2c0ad389a9b',
    messagingSenderId: '689549972098',
    projectId: 'fooddeliveryapp-1adf4',
    storageBucket: 'fooddeliveryapp-1adf4.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR44Ehjxtz05NcvOKBFkUeA9fBARJT7h8',
    appId: '1:689549972098:ios:f54e7ccc7bd2c0ad389a9b',
    messagingSenderId: '689549972098',
    projectId: 'fooddeliveryapp-1adf4',
    storageBucket: 'fooddeliveryapp-1adf4.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArwfED6RJFnWCi_-Is2U4d4DbNsw3boQs',
    appId: '1:689549972098:web:36f9644101ed33b2389a9b',
    messagingSenderId: '689549972098',
    projectId: 'fooddeliveryapp-1adf4',
    authDomain: 'fooddeliveryapp-1adf4.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-1adf4.appspot.com',
    measurementId: 'G-RDN3WVM2KG',
  );
}
